Order management
alisondraV/conestoga-insiders-club pull request #39
Opened 2021-11-23 22:52 UTC by ANDREYDEN

This is a BackEnd PR for some order stuff
- adds `OrderStatus` and `OrderType` to `Order`
- adds tests for `OrderService`
- adds helpful methods to `OrderService`

2021-11-23 22:58 UTC, MorganDWalker approved these changes

2021-11-24 00:53 UTC, alisondraV commented on WebUI/Data/DataAccess/OrderService.cs
> +        public OrderService(ApplicationDbContext context, IUserService userService)
It seems like it's not needed.

2021-11-24 00:54 UTC, alisondraV requested changes
Don't forget to run the formatting before putting up the PR.

2021-11-24 02:21 UTC, alisondraV approved these changes

2021-11-24 02:21 UTC, merged