Reports
alisondraV/conestoga-insiders-club pull request #41
Opened 2021-11-24 14:07 UTC by MorganDWalker

2021-12-02 02:22 UTC, alisondraV requested changes
Great work, everything works like a charm! 🎆 Considering the UI though, I would probably decrease the size of the headers, and make buttons' size consistent. Also, it would be great to space out these sections, cause it's a bit difficult to make sense of the page at the first sight.

2021-12-02 02:22 UTC, alisondraV commented on WebUI/Pages/AdminDashboard/AdminReports.razor
> +    <h3>Games Report</h3>
Heads up: you have two "Game Report" headers

2021-12-02 03:15 UTC, ANDREYDEN approved these changes
You have achieved functionality, but this will be hard to maintain in the future.
The comments that I left are for refactoring your code, so I'm completely fine to create a follow up PR, where you can clean this up. I would prioritize functionality over code readability at this point, so you can create that PR at your free time.

P.S. I doubt he's reading the code anyway

2021-12-03 22:19 UTC, alisondraV approved these changes

2021-12-03 22:20 UTC, merged