Email confirmation
alisondraV/conestoga-insiders-club pull request #47
Opened 2021-11-29 20:53 UTC by ANDREYDEN

- Adds SendGrid integration
- You'll need to set up an API key to have it working (reference `README` for instructions)

2021-11-29 20:55 UTC, ANDREYDEN commented
The majority of the code here was scaffolded. Changes to `Settings.razor` were required to make the scaffold not fail.

2021-12-01 17:15 UTC, alisondraV requested changes
I think it's important to add a descriptive message to this page, something like "Email has been confirmed, go to the Login Page now" or along those lines. I couldn't find this file, so it should probably be generated as well.

![image](https://user-images.githubusercontent.com/56138100/144281331-b8bbb1fe-ac5f-43db-9d01-4072569b4bfe.png)

2021-12-02 01:14 UTC, ANDREYDEN commented
I have also tested screens for password reset and email change

2021-12-02 01:50 UTC, alisondraV approved these changes

2021-12-02 02:56 UTC, SJETInc approved these changes

2021-12-02 03:27 UTC, merged